### ISSUE TITLE
QuestMean & QuestSd functions

### ISSUE THREAD

**Issue by lnahmad** [Psychtoolbox-3/psychtoolbox-3.github.com#4]
Greetings,

I would like to understand how the 'QuestMean' and 'QuestSd' functions work. There's not much information in the help sections of each function...
I've been calculating the threshold by running my data through a Weibull function and a Likelihood function I wrote. However, this only provides the thresholds (no variance, StDev, etc...).

Thank you very much in advance,

        lnahmad

**Comment by kleinerm** [comment]
Please send such questions to the Psychtoolbox user forum. Maybe 
somebody there can help you. It's unlikely anybody with expertise in 
Quest will read your question here.
