### ISSUE TITLE
Undocumented use option?

### ISSUE THREAD

**Issue by NirOfir** [Psychtoolbox-3/psychtoolbox-3.github.com#7]
I saw from the DatapixxShowGabor demo line 71
`texrect = Screen('Rect', gabortex);`
that Screen('Rect') can also be used to get the rectangle of a texture from its pointer, but this seems to be missing from the documentation on the website. I didn't understand from http://psychtoolbox.org/contribute if documentation updates can be sent as pull requests (here or to the other repository), or if users shouldn't edit the help texts, so I only opened the issue. Let me know if I should submit a pull request with an edited help text.

Thanks a lot!
Nir

**Comment by kleinerm** [comment]
Hi. Documentation that is part of Psychtoolbox can be sent as pull requests against Psychtoolbox-3/Psychtoolbx-3. In this case you'd update the help string in the C Code itself, as such docs are auto-generated from our code. General documentation updates to the website can be sent as pull requests against this repo. The Wiki of our website can be freely user edited. Thanks.

**Comment by kleinerm** [comment]
Added some added help text for next beta release.
